# Шрифт
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
font_size        14.0

# Скролл
scrollback_lines 100000000

# Отступы
window_padding_width 2

# Вкладки
tab_bar_edge top
tab_bar_style    powerline
tab_powerline_style slanted

# Курсор
cursor_shape     beam
cursor_blink_interval 0.5
copy_on_select yes

# Звук
enable_audio_bell no

# Shortcuts
map ctrl+v paste_from_clipboard
map ctrl+t new_tab
map ctrl+w close_tab
mouse_map right press ungrabbed paste_from_clipboard
